# Generated by Django 6.0.3 on 2026-05-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_for_message_edited_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_for',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
    ]
